/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData map_outline = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_vertical = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData name = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifications_outline = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pass_code = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData place_24px = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qr_code_scanner = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData report_problem_24px = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rotate = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_24px = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData security = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share_24px = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tiktok = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verify = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtube = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bio = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData capture = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chats = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contact_phone_24px = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copy = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData date_range_24px = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete_24px = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_outline = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData explore = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flash = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flash_off = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gallery = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_outline = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_filled = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
